// Strings shared by the page shell and every tool's UI.
export const COMMON = {
  en: {
    siteName: 'LocalKit',
    tagline: 'Free online tools that run in your browser',
    homeTitle: 'LocalKit — Free Online Tools That Never Upload Your Files',
    homeDesc: 'Free AI subtitles, PDF tools, image converter, video tools, resume builder, text diff and Base64 — all running privately in your browser. No upload, no sign-up, no watermark.',
    homeH1: 'Free tools that never upload your files',
    homeLead: 'Everything runs inside your browser. Your videos, PDFs and photos stay on your device — nothing is sent to a server, so it is private, fast and has no size quotas.',
    badges: ['No upload', 'No sign-up', 'No watermark', 'Free'],
    privacyBadge: 'Files stay on your device',
    allTools: 'All tools',
    howTo: 'How to use',
    faq: 'FAQ',
    related: 'Related tools',
    privacy: 'Privacy',
    source: 'Source code',
    footer: 'LocalKit — free tools that run in your browser. Open source, no tracking.',
    langName: 'English',
    otherLang: '中文',
    dropHere: 'Drop files here or click to choose',
    dropOne: 'Drop a file here or click to choose',
    chooseFile: 'Choose file',
    download: 'Download',
    downloadAll: 'Download all (ZIP)',
    processing: 'Processing…',
    done: 'Done',
    error: 'Something went wrong: $1',
    clear: 'Clear',
    copy: 'Copy',
    copied: 'Copied',
    remove: 'Remove',
    loadingEngine: 'Loading the processing engine (first time only)…',
    unsupported: 'Your browser does not support this feature. Please use a recent Chrome, Edge, Firefox or Safari.',
    noFiles: 'Add at least one file first.',
    privacyTitle: 'Privacy policy',
    privacyDesc: 'LocalKit processes files in your browser and does not collect personal data.',
    notFound: 'Page not found',
    categories: { ai: 'AI tools', pdf: 'PDF tools', image: 'Image tools', video: 'Video & audio', text: 'Text & developer', docs: 'Documents' },
  },
  zh: {
    siteName: 'LocalKit 本地工具箱',
    tagline: '在浏览器里运行的免费在线工具',
    homeTitle: 'LocalKit 本地工具箱 — 文件不上传的免费在线工具',
    homeDesc: '免费 AI 字幕生成、PDF 工具、图片格式转换、视频工具、简历制作、文本对比和 Base64，全部在浏览器本地运行。无需上传、无需注册、无水印。',
    homeH1: '文件不上传的免费在线工具',
    homeLead: '所有处理都在你的浏览器里完成。视频、PDF、照片都留在你的设备上，不会发送到任何服务器，所以更私密、更快，也没有大小和次数限制。',
    badges: ['不上传', '免注册', '无水印', '免费'],
    privacyBadge: '文件不离开你的设备',
    allTools: '全部工具',
    howTo: '使用方法',
    faq: '常见问题',
    related: '相关工具',
    privacy: '隐私政策',
    source: '源代码',
    footer: 'LocalKit 本地工具箱 — 在浏览器里运行的免费工具。开源，无追踪。',
    langName: '中文',
    otherLang: 'English',
    dropHere: '把文件拖到这里，或点击选择',
    dropOne: '把文件拖到这里，或点击选择',
    chooseFile: '选择文件',
    download: '下载',
    downloadAll: '全部下载（ZIP）',
    processing: '处理中…',
    done: '完成',
    error: '出错了：$1',
    clear: '清空',
    copy: '复制',
    copied: '已复制',
    remove: '移除',
    loadingEngine: '正在加载处理引擎（仅首次需要）…',
    unsupported: '你的浏览器不支持此功能，请使用新版 Chrome、Edge、Firefox 或 Safari。',
    noFiles: '请先添加至少一个文件。',
    privacyTitle: '隐私政策',
    privacyDesc: 'LocalKit 在你的浏览器中处理文件，不收集个人数据。',
    notFound: '页面不存在',
    categories: { ai: 'AI 工具', pdf: 'PDF 工具', image: '图片工具', video: '视频与音频', text: '文本与开发', docs: '文档' },
  },
};
